language: node_js

node_js:
  # Current LTS versions
  - "lts/boron"
  - "lts/carbon"
  # Supported until July 2018
  - "9"
  # Latest stable version
  - "node"

before_install:
  - npm i -g npm@6

install:
  - npm ci

script:
  - npm test
